// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"di-test/app"
	"go.uber.org/zap"
	"net/http"
)

// Injectors from wire.go:

func NewServer() *http.Server {
	v := NewRouterSlice()
	serveMux := app.NewServeMux(v)
	server := app.NewHTTPServer(serveMux)
	return server
}

func NewEchoHandler() app.Route {
	string2 := _wireStringValue
	echoHandler := app.NewEchoHandler(string2)
	return echoHandler
}

var (
	_wireStringValue = "echoPath"
)

func NewHelloHandler() app.Route {
	logger := NewLogger()
	helloHandler := app.NewHelloHandler(logger)
	return helloHandler
}

// wire.go:

func NewLogger() *zap.Logger {
	logger, err := zap.NewDevelopment()
	if err != nil {
		panic(err)
	}
	return logger
}

func NewRouterSlice() []app.Route {
	return []app.Route{NewEchoHandler(), NewHelloHandler()}
}
